# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: food-carts

plugins:
  - serverless-offline

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-west-2
  profile: serverless

# The `functions` block defines what code to deploy
functions:
  yelp:
    handler: yelp.save
    events:
      - schedule: rate(1 day)
  api:
    handler: api.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: search
          method: get
